services:
  # uv is the Python project management tool, similar to Poetry or Pipenv
  uv:
    profiles:
      - dev
    image: {{ cookiecutter.project_name }}/uv:latest
    environment:
      - UV_LINK_MODE=copy
      - UV_TOOL_BIN_DIR=/usr/local/bin
    build:
      dockerfile: dockerfiles/uv.Dockerfile
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    working_dir: /app
    entrypoint: ["uv"]
{%- if cookiecutter.use_gcloud -%}

  # Google Cloud CLI
  gcloud:
    profiles:
      - dev
    image: google/cloud-sdk:alpine
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    entrypoint: ["gcloud"]
{% endif %}
